from __future__ import annotations

import html
import re
from collections import defaultdict
from datetime import date, datetime
from pathlib import Path

from bxl_eda_worker.config import REPO_ROOT, Source
from bxl_eda_worker.digest import (
    CATEGORY_LABELS,
    CATEGORY_ORDER,
    TOPIC_LABELS,
    TOPIC_ORDER,
    _dedupe_by_title,
    _sort_for_section,
)
from bxl_eda_worker.models import Item

DOCS_DIR = REPO_ROOT / "docs"
ARCHIVE_DIR = DOCS_DIR / "archive"


def render_html(
    items: list[Item],
    sources: list[Source],
    *,
    window_start: datetime,
    window_end: datetime,
    headline: str = "",
) -> str:
    by_id = {s.id: s for s in sources}
    items = _dedupe_by_title(items)
    counts = {t: sum(1 for it in items if t in it.topics) for t in TOPIC_ORDER}
    swiss_items = [it for it in items if it.swiss_relevance]

    date_str = window_end.strftime("%Y-%m-%d")
    parts: list[str] = [
        "<!DOCTYPE html>",
        "<html lang=\"en\">",
        "<head>",
        "<meta charset=\"utf-8\">",
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
        f"<title>EU FP Digest — {date_str}</title>",
        "<link rel=\"stylesheet\" href=\"style.css\">",
        "</head>",
        "<body>",
        "<header>",
        "<h1>EU Foreign Policy &amp; Sanctions Digest</h1>",
        f"<div class=\"meta\">{date_str} · {_fmt(window_start)} → {_fmt(window_end)} UTC</div>",
        f"<div class=\"meta\">{len(items)} items · "
        f"Sanctions {counts['sanctions']} · Middle East {counts['middle_east']} · "
        f"FP {counts['foreign_policy']} · Swiss-relevance {len(swiss_items)}</div>",
        "<nav><a href=\"archive/\">Archive →</a></nav>",
        "</header>",
        "<main>",
    ]

    if headline:
        parts.append("<section class=\"headline\">")
        parts.append("<h2>Today</h2>")
        parts.append(f"<p class=\"lede\">{html.escape(headline)}</p>")
        parts.append("</section>")

    if swiss_items:
        parts.append("<section class=\"swiss-highlights\">")
        parts.append("<h2>🇨🇭 Swiss-relevance highlights</h2>")
        for it in _sort_for_section(swiss_items)[:15]:
            parts.append(_render_item_html(it, by_id))
        if len(swiss_items) > 15:
            parts.append(
                f"<p class=\"more\">… and {len(swiss_items) - 15} more in sections below.</p>"
            )
        parts.append("</section>")

    by_cat: dict[str, list[Item]] = defaultdict(list)
    for it in items:
        by_cat[it.category].append(it)

    for cat in CATEGORY_ORDER:
        cat_items = by_cat.get(cat, [])
        if not cat_items:
            continue
        parts.append(f"<section class=\"category cat-{html.escape(cat)}\">")
        parts.append(f"<h2>{html.escape(CATEGORY_LABELS[cat])}</h2>")
        for topic in TOPIC_ORDER:
            topic_items = [it for it in cat_items if topic in it.topics]
            if not topic_items:
                continue
            parts.append(f"<h3>{html.escape(TOPIC_LABELS[topic])}</h3>")
            for it in _sort_for_section(topic_items, by_id):
                parts.append(_render_item_html(it, by_id))
        parts.append("</section>")

    if not items:
        parts.append("<p class=\"empty\">No relevant items in this window.</p>")

    parts.append("</main>")
    polled = ", ".join(html.escape(s.name) for s in sources)
    parts.append(
        f"<footer>Generated by "
        f"<a href=\"https://github.com/aboutali/bxl_eda_worker\">bxl_eda_worker</a> · "
        f"sources polled: {polled}</footer>"
    )
    parts.append("</body></html>")
    return "\n".join(parts)


def render_archive_index(entries: list[dict]) -> str:
    """`entries`: list of {slug, label, sort_date, n_items, n_swiss, kind}."""
    parts: list[str] = [
        "<!DOCTYPE html>",
        "<html lang=\"en\"><head>",
        "<meta charset=\"utf-8\">",
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
        "<title>EU FP Digest — Archive</title>",
        "<link rel=\"stylesheet\" href=\"../style.css\">",
        "</head><body>",
        "<header>",
        "<h1>Archive</h1>",
        "<nav><a href=\"../\">← Latest</a></nav>",
        "</header>",
        "<main><ul class=\"archive-list\">",
    ]
    for e in entries:
        kind_tag = (
            ' <span class="kind kind-weekly">weekly</span>' if e["kind"] == "weekly" else ""
        )
        parts.append(
            f"<li><a href=\"{html.escape(e['slug'])}.html\">{html.escape(e['label'])}</a>"
            f"{kind_tag}"
            f" <span class=\"meta\">{e['n_items']} items · {e['n_swiss']} Swiss-relevance</span></li>"
        )
    parts.append("</ul></main>")
    parts.append("</body></html>")
    return "\n".join(parts)


def write_html_outputs(
    content: str,
    *,
    date: datetime,
    docs_dir: Path = DOCS_DIR,
) -> tuple[Path, Path]:
    docs_dir.mkdir(parents=True, exist_ok=True)
    archive = docs_dir / "archive"
    archive.mkdir(parents=True, exist_ok=True)
    index_path = docs_dir / "index.html"
    archive_path = archive / f"{date.strftime('%Y-%m-%d')}.html"
    index_path.write_text(content, encoding="utf-8")
    archive_path.write_text(content, encoding="utf-8")
    return index_path, archive_path


def refresh_archive_index(
    docs_dir: Path = DOCS_DIR,
    *,
    extract_counts=None,
) -> Path:
    archive = docs_dir / "archive"
    archive.mkdir(parents=True, exist_ok=True)
    extract = extract_counts or _peek_counts

    daily_re = re.compile(r"^(20\d\d-\d\d-\d\d)$")
    weekly_re = re.compile(r"^(20\d\d)-W(\d\d)$")

    entries: list[dict] = []
    for f in archive.glob("*.html"):
        if f.name == "index.html":
            continue
        slug = f.stem
        n_items, n_swiss = extract(f)
        if m := daily_re.match(slug):
            sort_date = date.fromisoformat(m.group(1))
            entries.append({
                "slug": slug, "label": slug, "sort_date": sort_date,
                "n_items": n_items, "n_swiss": n_swiss, "kind": "daily",
            })
        elif m := weekly_re.match(slug):
            year, week = int(m.group(1)), int(m.group(2))
            try:
                monday = date.fromisocalendar(year, week, 1)
                sunday = date.fromisocalendar(year, week, 7)
            except ValueError:
                continue
            entries.append({
                "slug": slug,
                "label": f"{slug} · {monday.strftime('%b %d')}–{sunday.strftime('%b %d')}",
                "sort_date": monday,
                "n_items": n_items, "n_swiss": n_swiss, "kind": "weekly",
            })
        # Anything else is ignored.

    entries.sort(key=lambda e: e["sort_date"], reverse=True)
    out = archive / "index.html"
    out.write_text(render_archive_index(entries), encoding="utf-8")
    return out


def _peek_counts(path: Path) -> tuple[int, int]:
    text = path.read_text(encoding="utf-8")
    m_items = re.search(r"(\d+) items", text)
    m_swiss = re.search(r"Swiss-relevance (\d+)", text)
    return (
        int(m_items.group(1)) if m_items else 0,
        int(m_swiss.group(1)) if m_swiss else 0,
    )


def _render_item_html(it: Item, by_id: dict[str, Source]) -> str:
    when = it.published_at or it.fetched_at
    src = by_id.get(it.source)
    source_name = src.name if src else it.source
    badge = f" <span class=\"badge\">{html.escape(src.badge)}</span>" if (src and src.badge) else ""
    lang = (
        f" <span class=\"lang\">{html.escape(it.language)}</span>"
        if (it.language and it.language != "en")
        else ""
    )
    importance = (
        f" <span class=\"importance\" title=\"importance {it.importance}/5\">{'★' * it.importance}</span>"
        if it.importance >= 4 else ""
    )

    title = html.escape(it.title)
    url = html.escape(it.url, quote=True)

    summary_text = it.summary_oneliner or it.summary
    summary = (
        f"<p class=\"summary\">{html.escape(summary_text)}</p>" if summary_text else ""
    )

    tags: list[str] = []
    if it.swiss_rationale:
        tags.append(
            f"<span class=\"tag-seco\">🇨🇭 {html.escape(it.swiss_rationale)}</span>"
        )
    elif it.swiss_relevance and "sanctions" in it.topics:
        tags.append("<span class=\"tag-seco\">SECO alignment likely</span>")
    if it.regions:
        tags.append("regions: " + html.escape(", ".join(it.regions)))
    tags_html = (
        f"<div class=\"tags\">{' · '.join(tags)}</div>" if tags else ""
    )

    return (
        "<article>"
        f"<h4><a href=\"{url}\">{title}</a></h4>"
        f"<div class=\"src\">{html.escape(source_name)}{badge}{lang}{importance}"
        f" · <time datetime=\"{when.isoformat()}\">{_fmt(when)}</time></div>"
        f"{summary}{tags_html}"
        "</article>"
    )


def _fmt(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d %H:%M")
